#exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
#paginate: 10
#destination: /home/ben/git-repos/keithmillar.github.com
#pygments: true
main_title: "Flo's Food and Drink"
description: "Flo's Recipes and Wine we like"

# Where things are

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

#Handling Reading

safe: false

# Serving

port: 4000
host: 0.0.0.0
baseurl: "" # does not include hostname

# Conversion

highlighter: true
excerpt_separator: "{{ more }}"
markdown_ext: markdown,mkd,mkdn,md
markdown: redcarpet

