main_title: "Flo's Food and Drink"
description: "Flo's Recipes and Wine we like"

markdown: redcarpet
highlighter: pygments
permalink: /:title

baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed



# Where things are

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

#Handling Reading

safe: false

# Serving

port: 4000
host: 0.0.0.0
url:
baseurl: "" # does not include hostname

# Conversion

highlighter: true
excerpt_separator: "{{ more }}"
markdown_ext: markdown,mkd,mkdn,md
markdown: redcarpet

