main_title: "Flo's Food and Drink"
description: "Flo's Recipes and Wine we like"

# Conversion
highlighter: pygments
excerpt_separator: "{{ more }}"
markdown_ext: markdown,mkd,mkdn,md
markdown: redcarpet
redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

# Serving
port: 4000
host: 0.0.0.0
url:
baseurl: "" # does not include hostname
permalink: /:title

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

#Handling Reading
safe: false





